add category entity
BohdanTrue/book-store-spring pull request #11
Opened 2023-12-27 22:35 UTC by BohdanTrue

2023-12-28 13:41 UTC, TarasYurkovskyi approved these changes
Well done)

2024-01-02 07:34 UTC, d1sam requested changes
Good job, but some changes should be done!

2024-01-02 07:34 UTC, d1sam commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +    @PostMapping("/{id}")
```suggestion
    @PutMapping("/{id}")
```

2024-01-02 07:34 UTC, d1sam commented on src/main/java/mate/academy/bookstore/dto/book/BookRequestDto.java
> +    @Pattern(regexp = "^(97(8|9))?\\d{9}(\\d|X)$", message = "Invalid ISBN format")
do we need this change in hw related to categories?

2024-01-02 07:34 UTC, d1sam commented on src/main/java/mate/academy/bookstore/exception/CategoryNotFoundException.java
You can use already existing exception `EntityNotFoundException`.

2024-01-02 07:34 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/Category.java
> +    private String description;
```suggestion
    @Column
    private String description;
```

2024-01-02 07:34 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/Category.java
> +@Data
```suggestion
@Data
@NoArgsConstructor
```

2024-01-02 07:34 UTC, d1sam commented on src/main/resources/db/changelog/changes/12-create-categories-table.yaml
> +                    nullable: false
```suggestion
```

2024-01-02 07:34 UTC, d1sam commented on src/main/resources/db/changelog/changes/13-create-books_categories-table.yaml
> +                    nullable: false
```suggestion
```

2024-01-02 07:34 UTC, d1sam commented on src/main/resources/db/changelog/changes/13-create-books_categories-table.yaml
> +                    nullable: false
```suggestion
```

2024-01-02 07:34 UTC, d1sam commented on src/main/resources/db/changelog/changes/12-create-categories-table.yaml
> +      author: Bohdan
```suggestion
      author: Bohdan Bilko
```

2024-01-02 07:34 UTC, d1sam commented on src/main/resources/db/changelog/changes/13-create-books_categories-table.yaml
> +      author: Bohdan
```suggestion
      author: Bohdan Bilko
```

2024-01-02 15:13 UTC, vovasalyha approved these changes

2024-01-02 15:14 UTC, merged