Implementing shopping cart
BohdanTrue/book-store-spring pull request #13
Opened 2024-01-03 11:47 UTC by BohdanTrue

create `ShoppingCartController ` and some points in it:
`GET: /api/books` - get info about users shopping cart
`POST: /api/books` - add an item to shopping cart
`PUT: /api/books/cart-items/{itemId}` - update quantity of item in shopping cart
`DELETE: /api/books/cart-items/{itemId}` - delete an item from shopping cart

2024-01-03 15:33 UTC, DevIgork approved these changes
LGTM

2024-01-04 08:50 UTC, d1sam requested changes
good job, but there are some changes should be done!

2024-01-04 08:50 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-04 08:50 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-04 08:50 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-01-04 08:50 UTC, d1sam commented on src/main/java/mate/academy/bookstore/repository/book/BookSpecificationBuilder.java
this change not related to this hw.

2024-01-04 08:50 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/Book.java
this change not related to this hw.

2024-01-04 13:25 UTC, vovasalyha approved these changes

2024-01-05 10:14 UTC, merged