Tests for shopping cart
BohdanTrue/book-store-spring pull request #19
Opened 2024-01-09 23:50 UTC by BohdanTrue

2024-01-10 16:12 UTC, annton-shakur approved these changes
good job!

2024-01-11 11:52 UTC, yevheniisynytsia requested changes
Great job!
Please consider applying comments to other files

2024-01-11 11:52 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual);
does it work fine when comparing list and array? looks good if so

2024-01-11 11:52 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/controller/ShoppingCartControllerTest.java
> +//    }
why is it commented?

2024-01-11 11:52 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/repository/book/BookRepositoryTest.java
> +        assertEquals("Robert Martin", actual.get(0).getAuthor());
compare the whole object with an expected one to be sure that it is ok completely

2024-01-11 11:52 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/service/impl/BookServiceImplTest.java
> +    private BookServiceImpl bookService;
place it under mocks

2024-01-11 11:52 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/service/impl/BookServiceImplTest.java
> +    @Test
display name

2024-01-11 16:01 UTC, BohdanTrue commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual);
Yeah, this method can also be used to compare lists or arrays that contain objects with corresponding getters and fields

2024-01-11 18:13 UTC, BohdanTrue commented on src/test/java/mate/academy/bookstore/repository/book/BookRepositoryTest.java
> +        assertEquals("Robert Martin", actual.get(0).getAuthor());
It doesn't refer to this HW, I already did it in my previous HW :D

2024-01-15 06:45 UTC, BohdanTrue commented
![image](https://github.com/BohdanTrue/book-store-spring/assets/94116191/ddfcc7fc-12de-4015-a805-111a7a4beb8f)
I have this problem which occurs on line 167 in my ShoppingCartControllerTest

2024-01-16 06:37 UTC, yevheniisynytsia approved these changes

2024-01-29 07:36 UTC, merged