add first version of README.md
BohdanTrue/book-store-spring pull request #20
Opened 2024-01-12 06:58 UTC by BohdanTrue

2024-01-12 07:44 UTC, yevheniisynytsia requested changes
Left some comments to work on =)

2024-01-12 07:44 UTC, yevheniisynytsia commented on README.md
> +  ___A comprehensive Library Management API tailored for seamless integration into digital platforms, perfect for powering online book repositories and literary platforms📚.___
I guess something went wrong and you have duplicated text

2024-01-12 07:44 UTC, yevheniisynytsia commented on README.md
> +- _OrderController_: manages order-related tasks, including the creation, modification, deletion, and retrieval of order history.
what about sections:

* Endpoints and what role can access them with a short description.
* Do you have a postman collection? If so, include it in the readme.
* How to run and test your application.
* What challenges you've faced and how you overcome them.
* Possible improvements.

2024-01-15 10:31 UTC, d1sam requested changes
good job, but some changes still should be done!

2024-01-15 10:31 UTC, d1sam commented on README.md
> +###👨‍💻Tech stack
what about testing technologies?

2024-01-15 10:31 UTC, d1sam commented on README.md
please add possible improvements section.

2024-01-17 06:57 UTC, yevheniisynytsia approved these changes
Well done! 1 comment left, please consider working on it

2024-01-17 06:57 UTC, yevheniisynytsia commented on README.md
> +###⚙️Possible Improvements
this is more "contribute to the project", but not "possible improvements"
you can add here smth like "I am going to make better search functionality, going to add a possibility to return the order" and so on

but you can also leave the text you have below the possible improvements, looks good!

2024-01-29 07:37 UTC, merged