implement global exception handler and data validation
BohdanTrue/book-store-spring pull request #5
Opened 2023-12-13 20:59 UTC by BohdanTrue

- Add CustomGlobalExceptionHandler class

- Add meaningful validation for existing DTO classes

2023-12-14 07:16 UTC, annton-shakur approved these changes
Good job!

2023-12-14 15:19 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2023-12-14 15:19 UTC, vovasalyha commented on pom.xml
> +            <groupId>org.hibernate.validator</groupId>
Prefer spring boot starters over direct dependencies

2023-12-14 15:19 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>      private String title;
For text fields I would suggest to validate length(size) too. Because you have length restrictions on DB level, so it's better to check it here too.

2023-12-14 15:19 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>      private String isbn;
ISBN field also has some other validation rules (like a format and size). So, validate it too.

2023-12-18 06:37 UTC, kshuryhin approved these changes
looks good

2023-12-18 07:25 UTC, merged