implementing JWT authorization
BohdanTrue/book-store-spring pull request #9
Opened 2023-12-26 00:50 UTC by BohdanTrue

2023-12-26 14:04 UTC, andrii-hoienko requested changes

2023-12-26 14:04 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto request) {
Please add Valid annotation to apply validation rules

2023-12-26 14:04 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/dto/user/UserLoginRequestDto.java
> +    @NotNull(message = "can't be null")
NotBlank validates null cases as well https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2023-12-26 14:04 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Please don`t forget about constants

2023-12-26 14:04 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-26 14:04 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-12-26 23:53 UTC, merged

2023-12-27 00:05 UTC, BohdanTrue commented
OMG I'm so sorry my PR was automatically closed. I was starting to fix my hw, but I didn't see in which branch I started to fix my errors. When i finished, I saw that I do this changes from previous branch in branch with JWT implementation. Also I fixed all of my problems in this branch and merged branch with JWT implementation to previous

2023-12-27 11:25 UTC, d1sam reviewed
Well done!